# Generated by Django 5.0.6 on 2024-07-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_alter_region_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region',
        ),
    ]
