# Generated by Django 5.0.6 on 2024-07-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_remove_region_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='comuna',
            new_name='region',
        ),
    ]
