# Generated by Django 5.0.6 on 2024-07-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_rename_comuna_comuna_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='region',
            new_name='comuna',
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble'),
        ),
    ]
