# Generated by Django 5.0.6 on 2024-07-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_rename_region_comuna_comuna_region_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='comuna',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.comuna'),
        ),
    ]
