# Generated by Django 5.0.6 on 2024-07-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_rename_comuna_comuna_region_remove_region_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_inmueble',
            name='tipo',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.tipo_inmueble'),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='nombre',
            field=models.CharField(default='casa', max_length=50),
        ),
    ]
