# Generated by Django 5.0.6 on 2024-07-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_remove_tipo_inmueble_tipo_inmueble_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tipoinmueble',
        ),
    ]
