# Generated by Django 5.0.6 on 2024-07-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_remove_inmueble_tipoinmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.tipo_usuario'),
        ),
    ]
